# Generated by Django 5.0 on 2025-11-17 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "visa_type",
                    models.CharField(
                        choices=[
                            ("H1B", "H-1B Work Visa"),
                            ("L1", "L-1 Intracompany Transfer"),
                            ("O1", "O-1 Extraordinary Ability"),
                            ("EB1", "EB-1 Employment Based First Preference"),
                            ("EB2", "EB-2 Employment Based Second Preference"),
                            ("EB3", "EB-3 Employment Based Third Preference"),
                            ("F1", "F-1 Student Visa"),
                            ("GREEN_CARD", "Green Card"),
                            ("CITIZENSHIP", "Citizenship"),
                            ("ASYLUM", "Asylum"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("INITIAL_CONSULTATION", "Initial Consultation"),
                            ("DOCUMENTS_GATHERING", "Documents Gathering"),
                            ("APPLICATION_PREP", "Application Preparation"),
                            ("FILED", "Filed"),
                            ("RFE", "Request for Evidence"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="INITIAL_CONSULTATION",
                        max_length=30,
                    ),
                ),
                ("country_of_origin", models.CharField(max_length=100)),
                ("case_number", models.CharField(max_length=50, unique=True)),
                ("filing_date", models.DateField(blank=True, null=True)),
                ("priority_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
